import Link from "next/link";
import SitePage from "../components/SitePage";

export const metadata = { title: "Website, App & Software Development Services", description: "Website development, Android and iOS apps, custom software and ongoing support for Delhi NCR businesses." };

const services = [
  { id: "websites", number: "01", title: "Website Development", intro: "From a static site to a dynamic business website or e-commerce store, build the right experience to help customers take the next step.", deliverables: ["Discovery, agreed page plan and responsive design", "Static, CMS/dynamic or e-commerce build", "Contact and enquiry flows, where scoped", "Basic on-page SEO, pre-launch testing and handover"], features: "Mobile-friendly layouts, clear navigation, WhatsApp/contact CTAs, analytics options, editable content, product catalogues and checkout, according to scope.", timeline: "Static: 2–3 weeks · Dynamic: 3–6 weeks · E-commerce: 4–8 weeks", price: "From ₹25,000 static · ₹60,000 dynamic · ₹90,000 e-commerce" },
  { id: "apps", number: "02", title: "Mobile App Development", intro: "Focused Android and iOS app experiences for customer journeys or internal business workflows.", deliverables: ["User flows and feature scope", "App interface design and development", "Agreed backend/API integrations", "Testing, release preparation and handover"], features: "Login, profiles, notifications, bookings/orders, dashboards and payment integration options, according to the approved scope.", timeline: "Typical first release: 8–16 weeks; timing depends on integrations and platform scope.", price: "App MVP from ₹1,50,000" },
  { id: "software", number: "03", title: "Custom Software", intro: "Portals, dashboards and internal tools that support your real processes instead of forcing a generic workflow.", deliverables: ["Process discovery and requirements document", "Role and workflow mapping", "Design and development of agreed modules", "Testing, deployment planning and handover"], features: "Role-based access, dashboards, reports, data-entry workflows, notifications and third-party integrations, as scoped.", timeline: "Initial release typically takes 6–14 weeks; larger systems can be delivered in phases.", price: "Custom software MVP from ₹1,00,000" },
  { id: "support", number: "04", title: "Maintenance & Support", intro: "Ongoing support for updates, fixes and planned improvements after launch, with a clearly defined monthly scope.", deliverables: ["Agreed support channel and response window", "Routine updates and checks", "Bug-fix allowance based on the selected plan", "Monthly work summary"], features: "Content updates, uptime checks, bug fixes, dependency updates and small improvements, according to the selected plan.", timeline: "Monthly retainer after onboarding; urgent incidents and larger features are scoped separately.", price: "From ₹4,999/month" },
];

export default function ServicesPage() {
  return <SitePage><main id="main"><section className="page-hero"><div className="container page-hero-inner"><p className="eyebrow"><span className="eyebrow-mark"/> Website, app & custom software / Delhi NCR</p><h1>Digital products built to <em>move your business forward.</em></h1><p>We bring the product experience behind SchoolOS to your website, app and software project. From discovery to launch and support, we keep the scope clear.</p><Link className="button button-accent" href="/contact?type=business">Get a Free Quote <span aria-hidden="true">-&gt;</span></Link></div></section>
    <section className="service-detail-list"><div className="container">{services.map((service) => <article className="service-detail" id={service.id} key={service.id}><div className="service-detail-heading"><span>{service.number} / SERVICE</span><h2>{service.title}</h2><p>{service.intro}</p></div><div className="service-detail-info"><h3>What’s included</h3><ul>{service.deliverables.map((item) => <li key={item}>{item}</li>)}</ul><h3>Features</h3><p>{service.features}</p><div className="service-facts"><p><b>Typical timeline</b>{service.timeline}</p><p><b>Starting price</b>{service.price}</p></div></div></article>)}</div></section>
    <section className="process-section"><div className="container"><p className="eyebrow eyebrow-light">Our delivery process</p><h2>Clarity at <em>every milestone.</em></h2><div className="process-grid">{[["01", "Discovery", "Understand goals, users, workflows and scope."], ["02", "Design", "Review user flows, screens and visual direction."], ["03", "Development", "Build and review the agreed scope in milestones."], ["04", "Launch", "Test, prepare the release and hand over the product."], ["05", "Support", "Plan maintenance, fixes and future improvements."]].map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="page-cta"><div className="container page-cta-inner"><div><p className="eyebrow">Start with a conversation</p><h2>Have a project idea? <em>Let’s define the scope.</em></h2><p>We’ll understand your goals and requirements, then share an estimate and suggested next steps.</p></div><Link className="button button-dark" href="/contact?type=business">Get a Free Quote <span aria-hidden="true">-&gt;</span></Link></div></section></main></SitePage>;
}