import Link from "next/link";
import SitePage from "../components/SitePage";

export const metadata = { title: "Resources for School & Business Digital Projects", description: "Practical planning prompts for websites, mobile apps and school management workflows." };
const resources = [
  { id: "website-planning", kind: "Website planning", title: "What should you prepare before building a website?", intro: "Use these six prompts to make your project brief more useful.", points: ["The website’s primary goal: enquiries, bookings, sales or information.", "Who will use the site and what action should they take?", "Required pages and an owner for each page.", "Existing logo, photos, copy and brand guidelines.", "Reference sites and what you like or dislike about them.", "Budget range, decision-maker and preferred launch window."], takeaway: "You do not need every detail finalised. Listing priorities and open questions helps focus discovery." },
  { id: "mobile-app", kind: "App discovery", title: "When does a business need a mobile app?", intro: "Consider an app when a repeat customer or staff workflow benefits from a dedicated mobile experience.", points: ["Do users repeat this workflow often?", "Would an app offer clear value beyond a mobile-friendly website?", "Could a responsive website validate the idea first?", "What is the single most important user journey for the MVP?", "Which login, notification, payment or integration features are required?", "Who will maintain the app after launch?"], takeaway: "Validate one primary user journey before committing to a long feature list." },
  { id: "school-workflows", kind: "School operations", title: "Bringing school workflows into one platform", intro: "Map daily handoffs and information flows before discussing a school management platform.", points: ["The process from admission enquiry to enrolment.", "Who records attendance and who needs to view it?", "How are fee updates and reminders communicated?", "What information do teachers and parents need, and when?", "How should student, staff and parent access differ?", "Where do duplicate entries or delays happen today?"], takeaway: "Mapping the process with real users makes product demos and rollouts more relevant." },
];

export default function ResourcesPage() {
  return <SitePage><main id="main"><section className="page-hero resources-hero"><div className="container page-hero-inner"><p className="eyebrow"><span className="eyebrow-mark"/> Bytrova resources</p><h1>Start with <em>better questions.</em></h1><p>Practical planning prompts for website, app and school operations projects.</p></div></section><section className="resources-list"><div className="container">{resources.map((resource, index) => <article className="resource-guide" id={resource.id} key={resource.id}><div className="resource-guide-index"><span>{String(index + 1).padStart(2, "0")}</span><span>{resource.kind}</span></div><div><h2>{resource.title}</h2><p className="resource-guide-intro">{resource.intro}</p><ul>{resource.points.map((point) => <li key={point}>{point}</li>)}</ul><p className="resource-takeaway"><b>Takeaway:</b> {resource.takeaway}</p></div></article>)}</div></section><section className="page-cta"><div className="container page-cta-inner"><div><p className="eyebrow">Have a project in mind?</p><h2>From planning prompts to <em>project discussion.</em></h2></div><Link className="button button-dark" href="/contact?type=business">Talk to Bytrova <span aria-hidden="true">-&gt;</span></Link></div></section></main></SitePage>;
}