import Link from "next/link";
import SitePage from "../components/SitePage";

export const metadata = { title: "About Bytrova", description: "Learn how Bytrova's SchoolOS product experience informs our website, app and custom software work." };
const values = [["01", "Useful by design", "Every feature should connect to a real user or business need."], ["02", "Clarity", "Discuss scope, timelines, trade-offs and costs upfront."], ["03", "Dependability", "Make quality, privacy and maintainability part of the work."], ["04", "Collaboration", "Bring customer feedback and domain knowledge into the process."], ["05", "Steady progress", "Deliver larger projects through manageable milestones."]];

export default function AboutPage() {
  return <SitePage><main id="main"><section className="page-hero about-hero"><div className="container page-hero-inner"><p className="eyebrow"><span className="eyebrow-mark"/> About Bytrova</p><h1>Product thinking, <em>practical software.</em></h1><p>Our journey began with SchoolOS and now includes digital projects for schools and Delhi NCR businesses.</p></div></section>
    <section className="story-section"><div className="container story-layout"><div><p className="eyebrow">Our story</p><h2>From SchoolOS to business services.</h2></div><div className="story-copy"><p>Bytrova began with a practical challenge in education operations: helping administrators, teachers, students and parents access connected workflows for everyday school needs.</p><p>Building SchoolOS meant organising multiple user roles and connected processes in software. We now bring that product-building approach to websites, apps and custom software for Delhi NCR businesses.</p><p>Every organisation works differently. We start by understanding the problem and its users, then scope a practical solution.</p></div></div></section>
    <section className="mission-section"><div className="container mission-grid"><article><p className="eyebrow eyebrow-light">Mission</p><h2>Build useful, reliable software that makes daily work <em>easier.</em></h2><p>Support teams in their work and give their customers a better digital experience.</p></article><article><p className="eyebrow eyebrow-light">Vision</p><h2>Technology that <em>fits the work.</em></h2><p>Give every organisation thoughtfully designed software for its needs, without unnecessary complexity.</p></article></div></section>
    <section className="team-section"><div className="container team-layout"><div><p className="eyebrow">How we work</p><h2>A focused team. <em>Clear ownership.</em></h2><p>We bring the right skills to each project stage. Roles, ownership and the project contact are confirmed at kickoff.</p></div><div className="team-roles">{[["Product & Discovery", "Define business goals, user needs and project scope."], ["Design", "Make user flows and interfaces clear and usable."], ["Engineering", "Build the website, app or software to the agreed scope."], ["Delivery & Support", "Coordinate testing, launch and post-launch communication."]].map(([role, text]) => <article key={role}><h3>{role}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="values-section"><div className="container"><p className="eyebrow">What guides us</p><h2>Our <em>values.</em></h2><div className="values-grid">{values.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="page-cta"><div className="container page-cta-inner"><div><p className="eyebrow">Talk to Bytrova</p><h2>Let’s understand your project <em>and plan the next step.</em></h2></div><Link className="button button-dark" href="/contact">Contact our team <span aria-hidden="true">-&gt;</span></Link></div></section></main></SitePage>;
}