export const portfolioProjects = [
  {
    slug: "tabletrail",
    name: "TableTrail",
    type: "Websites",
    label: "Website concept",
    headline: "A restaurant experience from menu to enquiry.",
    description: "A proposed restaurant website experience for guests to browse a menu, find the venue and send a reservation enquiry.",
    problem: "Restaurant guests may have to jump between social posts, menu images and maps just to decide where to eat or how to book.",
    approach: "Bring the menu, venue details and reservation path into one mobile-first experience, with clear hierarchy and a simple next action.",
    solution: "A responsive restaurant website concept that connects menu discovery, location information and a reservation enquiry flow.",
    features: ["Digital menu", "Reservation enquiry", "Location and hours", "Mobile-first layout"],
    technology: "Illustrative React and CSS concept. A production technology stack would be selected after project discovery.",
    screens: ["Home", "Menu", "Dish detail", "Reservation enquiry", "Contact"],
    outcome: "Design objective: help guests find the information they need and reach the restaurant with less friction. No client launch or business result is claimed.",
    theme: "tomato",
    preview: "A better seat at the table.",
    action: "Explore menu",
  },
  {
    slug: "reproute",
    name: "RepRoute",
    type: "Mobile Apps",
    label: "Mobile app concept",
    headline: "Gym discovery and member planning in one app.",
    description: "A proposed gym app experience for exploring memberships, class schedules and member booking journeys.",
    problem: "Gym members can find it difficult to compare plans and keep class information and booking details together.",
    approach: "Shape the experience around the member's key tasks: discover a class, understand availability and plan the next visit.",
    solution: "A mobile app concept connecting membership plans, class timetables, trainer profiles and a booking flow.",
    features: ["Membership plans", "Class timetable", "Trainer profiles", "Booking flow"],
    technology: "Illustrative React and CSS concept. A production technology stack would be selected after project discovery.",
    screens: ["Discover", "Plans", "Class schedule", "Trainer profile", "Booking"],
    outcome: "Design objective: make it easier for members to find and plan a suitable class. No client launch or membership result is claimed.",
    theme: "blue",
    preview: "Find your next session.",
    action: "View classes",
  },
  {
    slug: "glowdesk",
    name: "GlowDesk",
    type: "Web Apps",
    label: "Booking web app concept",
    headline: "Salon services with a simpler booking journey.",
    description: "A proposed salon discovery and booking experience for service selection, stylist profiles and appointment requests.",
    problem: "Clients need a clear way to compare services and stylists before requesting an appointment.",
    approach: "Organise service details and stylist information around the appointment decision, with a direct, low-friction request path.",
    solution: "A responsive booking web app concept with service discovery, stylist profiles and an appointment request flow.",
    features: ["Service menu", "Stylist profiles", "Appointment request", "Booking confirmation"],
    technology: "Illustrative React and CSS concept. A production technology stack would be selected after project discovery.",
    screens: ["Services", "Stylist", "Appointment", "Confirmation", "Client account"],
    outcome: "Design objective: help clients make an informed choice and request an appointment in fewer steps. No client launch or booking result is claimed.",
    theme: "green",
    preview: "Good care, made simple.",
    action: "Book an appointment",
  },
  {
    slug: "opsatlas",
    name: "OpsAtlas",
    type: "Custom Software",
    label: "Business software concept",
    headline: "A shared view of the work moving through a business.",
    description: "A proposed internal operations dashboard concept for teams tracking requests, ownership and next steps.",
    problem: "Requests and handoffs spread across messages and spreadsheets can make ownership and progress hard to see.",
    approach: "Model an operational view around status, responsible owner and next action, with useful summaries for the team.",
    solution: "A custom software dashboard concept connecting work queues, team ownership and request status in one interface.",
    features: ["Work queue", "Status tracking", "Team ownership", "Operational summary"],
    technology: "Illustrative React and CSS concept. A production technology stack would be selected after project discovery.",
    screens: ["Overview", "Work queue", "Request detail", "Team view", "Reports"],
    outcome: "Design objective: make work status and ownership easier to scan. No client deployment or productivity result is claimed.",
    theme: "ink",
    preview: "Know what moves next.",
    action: "View work queue",
  },
];

export const portfolioFilters = ["All", "Websites", "Mobile Apps", "Web Apps", "Custom Software"];