import Link from "next/link";
import SitePage from "../components/SitePage";

export const metadata = { title: "Website, App & Software Development Pricing", description: "Indicative starting prices for website, app, custom software and maintenance projects in Delhi NCR." };

const packages = [
  { service: "Websites", tiers: [["Starter", "From ₹25,000", "Up to 5 pages · responsive layout · contact/enquiry · basic on-page SEO"], ["Growth", "From ₹60,000", "Up to 10 pages · dynamic/CMS option · analytics setup · enquiry flow"], ["Pro / Store", "From ₹90,000", "E-commerce catalogue · checkout scope · payment gateway setup · admin handover"]] },
  { service: "Mobile apps", tiers: [["Starter", "From ₹1,50,000", "MVP · core screens · one primary user flow · basic backend/API"], ["Growth", "From ₹3,00,000", "Expanded feature set · multiple user flows · selected integrations · QA"], ["Pro", "From ₹5,50,000", "Larger feature scope · advanced roles · integrations · release planning"]] },
  { service: "Custom software", tiers: [["Starter", "From ₹1,00,000", "One core workflow · basic roles · focused dashboard or portal"], ["Growth", "From ₹2,50,000", "Multiple workflows · role-based access · reports · selected integrations"], ["Pro", "From ₹5,00,000", "Multi-module scope · advanced permissions/reports · phased rollout planning"]] },
];
const pricingFaqs = [
  ["Are listed prices final?", "No. These are indicative starting estimates. We confirm the final cost after reviewing requirements, integrations, content and timeline."],
  ["Is GST included?", "No. GST is extra, if applicable. Tax treatment will be confirmed before the proposal or invoice."],
  ["Are domain, hosting and third-party services included?", "Only when they are explicitly listed in the quote. Domain, hosting, payment gateway, SMS, maps and app-store accounts may cost extra."],
  ["How do payment milestones work?", "The proposal defines delivery milestones and the payment schedule. Work starts under the agreed terms and approved scope."],
  ["Can I add features during a project?", "Yes. We’ll estimate the change and update the cost or timeline after approval."],
  ["Is maintenance mandatory?", "No, unless a specific proposal says otherwise. Monthly support plans are available."],
];

export default function PricingPage() {
  return <SitePage><main id="main"><section className="page-hero"><div className="container page-hero-inner"><p className="eyebrow"><span className="eyebrow-mark"/> Pricing / Delhi NCR</p><h1>Clear starting prices. <em>Final quotes based on scope.</em></h1><p>Every business project is different. Use these indicative ranges for planning; we’ll confirm the final price after discovery and scope approval.</p><Link className="button button-accent" href="/contact?type=business">Get a Free Quote <span aria-hidden="true">-&gt;</span></Link></div></section>
    <section className="pricing-section"><div className="container">{packages.map((group) => <section className="price-group" key={group.service}><div className="price-group-heading"><p className="eyebrow">Service packages</p><h2>{group.service}</h2></div><div className="price-cards">{group.tiers.map(([tier, price, features]) => <article className="price-card" key={tier}><span className="price-tier">{tier}</span><strong>{price}</strong><p>{features}</p><Link href="/contact?type=business">Discuss this tier <span aria-hidden="true">-&gt;</span></Link></article>)}</div></section>)}
      <section className="price-group maintenance-group"><div className="price-group-heading"><p className="eyebrow">After launch</p><h2>Maintenance plans</h2><p>Support hours, response windows and exclusions are defined in the agreement.</p></div><div className="maintenance-table"><div className="maintenance-row maintenance-head"><span>Plan</span><span>Price / month</span><span>Indicative scope</span></div><div className="maintenance-row"><strong>Essential</strong><strong>From ₹4,999</strong><span>Routine checks, updates, agreed small fixes, monthly summary</span></div><div className="maintenance-row"><strong>Growth</strong><strong>From ₹9,999</strong><span>Essential scope plus larger support allowance and regular improvement time</span></div><div className="maintenance-row"><strong>Priority</strong><strong>From ₹19,999</strong><span>Priority response window, higher support allowance, planned improvement time</span></div></div></section>
      <section className="bundle-panel"><div><p className="eyebrow">Combined projects</p><h2>Bundle offers, <em>planned around scope.</em></h2></div><div><p>Request a combined estimate for a website and maintenance plan, a website and app, or a business launch bundle. If design or backend work can be shared, we’ll show any potential savings in the proposal.</p><p>SchoolOS customers can request a separate scoped estimate for custom integrations or additional software.</p></div></section>
      <section className="pricing-faq"><div><p className="eyebrow">Before you decide</p><h2>Common pricing <em>questions.</em></h2></div><div className="faq-list">{pricingFaqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section><p className="pricing-disclaimer">Prices are in INR, GST extra if applicable. Hosting, domain, paid plugins/services, app-store accounts, content production and third-party charges are excluded unless the proposal says otherwise. Final scope and quote will be confirmed in writing.</p></div></section>
    <section className="page-cta"><div className="container page-cta-inner"><div><p className="eyebrow">Free initial discussion</p><h2>Share your requirements. <em>We’ll prepare an estimate.</em></h2></div><Link className="button button-dark" href="/contact?type=business">Get a Free Quote <span aria-hidden="true">-&gt;</span></Link></div></section></main></SitePage>;
}